services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bay
      POSTGRES_PASSWORD: "tNqj18bAz3KcF_CuHoLW1jpT_lCkyt5X"
    volumes:
      - bay_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "aOZFTjDUzm1Jdlfz0Xn1hm3YOtpPyS6E"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bay_test
      POSTGRES_PASSWORD: "uEble1OMVxA-SIrMYNr-jAlictFRlv4F"
    volumes:
      - bay_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "ZNSrQfo_F4P_DLCgntEEyWXYBNl5F9Vm"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  bay_data:
  bay_test_data:
